// Curated country list for agent country fields (alphabetical order).

export const COUNTRIES = [
  'Algeria',
  'Australia',
  'Bahrain',
  'Canada',
  'China',
  'Egypt',
  'France',
  'Germany',
  'Hong Kong',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Israel',
  'Italy',
  'Japan',
  'Jordan',
  'Korea, Republic of',
  'Kuwait',
  'Lebanon',
  'Libya',
  'Malaysia',
  'Morocco',
  'Oman',
  'Pakistan',
  'Philippines',
  'Qatar',
  'Russia',
  'Saudi Arabia',
  'Singapore',
  'Spain',
  'Sudan',
  'Syria',
  'Taiwan',
  'Thailand',
  'Tunisia',
  'Turkey',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Vietnam',
  'Yemen',
] as const

export const COUNTRY_DATALIST_ID = 'countries-list'
